server:
  port: 9000

person:
  name: '小明@163.com'
  age: 14
  map:
    k1: v1
    k2: v2
  animal:
    name: '狗'
    age: 2

# 使用---为yml文件分文档
spring:
  profiles:
    active: prod
---
spring:
  profiles: dev
server:
  port: 8001

---
spring:
  profiles: prod
server:
  port: 8002
